#!/usr/bin/env node
/**
 * Convert a .raw PCM audio file to the JSON format used by the demo waveform player.
 *
 * Usage:
 *   node src/demo/convert.js <input.raw> <output.json> [sampleRate] [encoding]
 *
 * Arguments:
 *   input.raw    — raw PCM file (no header, just samples)
 *   output.json  — where to write (e.g. pcg_aortic.json or ecg_aortic.json)
 *   sampleRate   — samples per second (default: 4000 for PCG, 500 for ECG)
 *   encoding     — int16 | float32 (default: int16)
 *
 * Examples:
 *   node src/demo/convert.js aortic_pcg.raw pcg_aortic.json 4000 int16
 *   node src/demo/convert.js aortic_ecg.raw ecg_aortic.json 500 int16
 *   node src/demo/convert.js signal.raw pcg_aortic.json 2000 float32
 *
 * The .raw file is expected to be little-endian 16-bit signed integers (PCM16)
 * or 32-bit IEEE 754 floats, with no file header.
 * Most stethoscope / audio recorder apps can export in this format.
 */

const fs   = require('fs');
const path = require('path');

const [,, inputFile, outputFile, sampleRateArg, encodingArg] = process.argv;

if (!inputFile || !outputFile) {
  console.error('Usage: node convert.js <input.raw> <output.json> [sampleRate] [encoding]');
  process.exit(1);
}

const sampleRate = parseInt(sampleRateArg ?? '4000', 10);
const encoding   = (encodingArg ?? 'int16').toLowerCase();

if (!['int16', 'float32'].includes(encoding)) {
  console.error('Encoding must be int16 or float32');
  process.exit(1);
}

const buf = fs.readFileSync(path.resolve(inputFile));

let samples;
if (encoding === 'int16') {
  const count = Math.floor(buf.length / 2);
  samples = new Array(count);
  for (let i = 0; i < count; i++) {
    samples[i] = buf.readInt16LE(i * 2) / 32768;          // normalize to [-1, 1]
    samples[i] = Math.round(samples[i] * 1e5) / 1e5;      // 5 decimal places is plenty
  }
} else {
  const count = Math.floor(buf.length / 4);
  samples = new Array(count);
  for (let i = 0; i < count; i++) {
    const v = buf.readFloatLE(i * 4);
    samples[i] = Math.round(Math.max(-1, Math.min(1, v)) * 1e5) / 1e5;
  }
}

const output = {
  label:      path.basename(inputFile, '.raw'),
  note:       'Generated by src/demo/convert.js — replace samples[] with your own recording.',
  sampleRate,
  samples,
};

fs.writeFileSync(path.resolve(outputFile), JSON.stringify(output));

const durationSec = (samples.length / sampleRate).toFixed(1);
console.log(`✓  ${samples.length} samples @ ${sampleRate} Hz = ${durationSec}s → ${outputFile}`);
